### ISSUE TITLE
LGT8F328P surport MIXLY sofware

### ISSUE THREAD

**Issue by beijia4319** [nulllaborg/arduino_nulllab#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
when we use mixly on LGT8 board ,the PE port can not be used, can you add the LGT8 surport to the MIXLY  in short time.thank you

**Comment by nulllaborg** [comment]
support please read this  https://github.com/nulllaborg/arduino_nulllab/blob/master/README_zh.md  mixly part
