### ISSUE TITLE
32M internal RC and 32M CPU Speed, 9600 baud rate not working

### ISSUE THREAD

**Issue by h11544** [nulllaborg/arduino_nulllab#19]
If set 32M internal RC and 32M CPU Speed, if use serial port, the 9600bps not working. Only if select 16M CPU Speed.
In 32M internal RC and 32M CPU speed, only 56000 bps baud rate is working.

**Comment by happysoul** [comment]
same bug with 32M & 32M
跟楼上一样 选了32M内置晶振和32M主频，串口输出乱码，选成 16M的工作频率 串口输出输出才正常一点
打开串口收到的第一行还是个乱码，后续才正常

**Comment by nulllaborg** [comment]
fix on 1117dd6d02aac8e8135fdd26862324ea6faed4c4
