### ISSUE TITLE
MsTimer2 编译报错

### ISSUE THREAD

**Issue by lzty634158** [nulllaborg/arduino_nulllab#5]
wiring.c.o (symbol from plugin): In function `__vector_9':
(.text+0x0): multiple definition of `__vector_9'
libraries\MsTimer2\MsTimer2.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
exit status 1
为开发板 Nulllab Nano 编译时出错。

**Comment by nulllaborg** [comment]
fix  on commit 3c2857fb204c3436a91d6b7854c4389be5295ae6
